/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package Controlador;
import Vista.*;
import Modelo. Conexion.Conexion;
import Vista.Cliente;
import Vista.Agente_Cobrador;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jeremy
 */
public class Funeraria extends javax.swing.JFrame {
 private Cliente Cliente;
 private Agente_Cobrador Agente_Cobrador;
 private Beneficiarios Beneficiarios;
 private Contrato Contrato;
 private Modelo Modelo;
 private Pagos Pagos;
 private Servicio_Ataud Servicio_Ataud;
 
   
        
    /**
     * Creates new form Funeraria
     */
    public Funeraria() throws SQLException {
        initComponents();
        setTitle("Funeraria");
        
        
        Agente_Cobrador= new Agente_Cobrador();
        desktopPane.add(Agente_Cobrador);
        
        Beneficiarios= new Beneficiarios();
        desktopPane.add(Beneficiarios);
        
        Cliente= new Cliente();
        desktopPane.add(Cliente);
        
        Contrato= new Contrato();
        desktopPane.add(Contrato);
        
        Modelo= new Modelo();
        desktopPane.add(Modelo);
        
        Pagos= new Pagos();
        desktopPane.add(Pagos);
        
        Servicio_Ataud= new Servicio_Ataud();
        desktopPane.add(Servicio_Ataud);    
    }
    

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        desktopPane = new javax.swing.JDesktopPane();
        desktopPane1 = new javax.swing.JDesktopPane();
        desktopPane2 = new javax.swing.JDesktopPane();
        jButton2 = new javax.swing.JButton();
        jButtonCliente = new javax.swing.JButton();
        jButtonAgente = new javax.swing.JButton();
        jButtonBeneficiario = new javax.swing.JButton();
        jButtonModelo = new javax.swing.JButton();
        jButtonPagos = new javax.swing.JButton();
        jButtonServicios = new javax.swing.JButton();
        jButtonContrato = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("jButton1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        desktopPane2.add(jButton2);
        jButton2.setBounds(20, 30, 75, 23);

        desktopPane1.add(desktopPane2);
        desktopPane2.setBounds(0, 0, 0, 0);

        jButtonCliente.setText("Cliente");
        jButtonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClienteActionPerformed(evt);
            }
        });
        desktopPane1.add(jButtonCliente);
        jButtonCliente.setBounds(20, 20, 70, 40);

        jButtonAgente.setText("Agente");
        jButtonAgente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgenteActionPerformed(evt);
            }
        });
        desktopPane1.add(jButtonAgente);
        jButtonAgente.setBounds(20, 80, 72, 23);

        jButtonBeneficiario.setText("Beneficiario");
        jButtonBeneficiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBeneficiarioActionPerformed(evt);
            }
        });
        desktopPane1.add(jButtonBeneficiario);
        jButtonBeneficiario.setBounds(20, 140, 80, 23);

        jButtonModelo.setText("Modelo");
        jButtonModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModeloActionPerformed(evt);
            }
        });
        desktopPane1.add(jButtonModelo);
        jButtonModelo.setBounds(20, 200, 72, 23);

        jButtonPagos.setText("Pagos");
        jButtonPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPagosActionPerformed(evt);
            }
        });
        desktopPane1.add(jButtonPagos);
        jButtonPagos.setBounds(20, 250, 72, 23);

        jButtonServicios.setText("Servicios");
        jButtonServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonServiciosActionPerformed(evt);
            }
        });
        desktopPane1.add(jButtonServicios);
        jButtonServicios.setBounds(20, 300, 76, 23);

        jButtonContrato.setText("Contrato");
        jButtonContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContratoActionPerformed(evt);
            }
        });
        desktopPane1.add(jButtonContrato);
        jButtonContrato.setBounds(20, 350, 80, 23);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClienteActionPerformed
      Cliente.setVisible(true);
        try{
            Cliente.obtenerDatos();
        }catch(SQLException ex){
            Logger.getLogger(Funeraria.class.getName()).
                    log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonClienteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonAgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgenteActionPerformed
        Agente_Cobrador.setVisible(true);
        try{
            Agente_Cobrador.obtenerDatos();
        }catch(SQLException ex){
            Logger.getLogger(Funeraria.class.getName()).
                    log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAgenteActionPerformed

    private void jButtonBeneficiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBeneficiarioActionPerformed
       Beneficiarios.setVisible(true);
    }//GEN-LAST:event_jButtonBeneficiarioActionPerformed

    private void jButtonModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModeloActionPerformed
        Modelo.setVisible(true);
    }//GEN-LAST:event_jButtonModeloActionPerformed

    private void jButtonPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPagosActionPerformed
       Pagos.setVisible(true);
    }//GEN-LAST:event_jButtonPagosActionPerformed

    private void jButtonServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonServiciosActionPerformed
        Servicio_Ataud.setVisible(true);
    }//GEN-LAST:event_jButtonServiciosActionPerformed

    private void jButtonContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContratoActionPerformed
        Contrato.setVisible(true);
    }//GEN-LAST:event_jButtonContratoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Funeraria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Funeraria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Funeraria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Funeraria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Funeraria().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Funeraria.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JDesktopPane desktopPane1;
    private javax.swing.JDesktopPane desktopPane2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAgente;
    private javax.swing.JButton jButtonBeneficiario;
    private javax.swing.JButton jButtonCliente;
    private javax.swing.JButton jButtonContrato;
    private javax.swing.JButton jButtonModelo;
    private javax.swing.JButton jButtonPagos;
    private javax.swing.JButton jButtonServicios;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

  

   
}